### ISSUE TITLE
Mouse events wheel up/down and mbx1/2 can be bound in Configuration→Keybindings but won't work in game

### ISSUE THREAD

**Issue by leovilok** [clintbellanger/flare-engine#1023]
Special mouse events 'wheel up', 'wheel down', 'mbx1', 'mbx2' (extra middle mouse buttons) can be selected in Configuration→Keybindings (the previously given names are what shows up) but will have no effect in game. Surprisingly, middle mouse button ('mmb') will work.

Flare alpha v0.19 on Arch Linux

**Comment by dorkster** [comment]
With https://github.com/clintbellanger/flare-engine/commit/8c9020f5b6e6ba44f57c3762a871e3c7ab0886d7, we should have support for binding all extra mouse buttons.

However, since we moved to SDL 2, `SDL_MOUSEWHEEL` events are separate from the normal mouse button events, so it's no longer possible to bind mouse wheel up/down to actions.

The original problem addressed by this issue was that it was possible to bind keys, but they were then unusable in-game. That problem has been resolved, so I'll close this.
