### ISSUE TITLE
character partly hidden by front of tent

### ISSUE THREAD

**Issue by sudoman** [clintbellanger/flare-engine#1279]
the character can stand next to a tent and be [partly covered](http://imgur.com/gvg3dzX) by the tent image.

![covered by front of tent](http://imgur.com/gvg3dzX.png)

**Comment by sudoman** [comment]
what if the side of the tent wasn't split into two trapezoids but was instead split into two parallelograms? i think that would fix the issue.

**Comment by clintbellanger** [comment]
A quick fix would be to alter some of these tiles so the player can't get close to the spliced edges. E.g. maybe by making the tent take up a 2x2 area instead of 2x1. Or to be more careful with the way tiles are spliced, or leave it at a single tile.

An entity radius for movement/collision could help a little, keeping the character away from those tile edges.

Down the road we can consider introducing a more complex tile-ordering algorithm that could handle this case. It would be a big change to handle just a few corner cases.

**Comment by sudoman** [comment]
another option could be to draw the tent behind the player unless the player is on the other side of the tent (i.e. north of the line between the WNW and ESE corners).

although i'm not sure there's an elegant way to handle that approach.

**Comment by dorkster** [comment]
I've made some progress on fixing this: [commit](https://github.com/dorkster/flare-engine/commit/168c775fcc6eb540e2cfeb6300e258fa387f9036) | [demo video](https://youtu.be/NF_cXyhCokA)

Not upstream yet because it still needs some work with handling unpacked tiles.

**Comment by dorkster** [comment]
Happy to say this is finally fixed as of version 1.04.05.

Relevant commits for future reference:

- 168c775fcc6eb540e2cfeb6300e258fa387f9036
- ec73cf902da6854c9d1d1eb308d25375a7972835
- b1a50fe4c1ab195bf940cdf83a582b7bb3ea4d8d
