### ISSUE TITLE
Arrows stuck in "black wall" located on map spawn point

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1332]
Spawn point without tiles is treated as wall. Can we do something with this?

**Comment by dorkster** [comment]
I don't think I understand the issue here. Does "without tiles" just mean no visual tiles? Or does it mean that there is also no explicit collision tile there? If you look at the collision layer in Tiled:
- red tiles are "walls" that powers (like arrows) will collide with.
- blue tiles are "pits" that powers can pass over
If the tiles(s) in question are visibly an open area, it may make sense to fill those in as blue.

**Comment by igorko** [comment]
Go to the  end of Death Valley map in noname mod and wait for Skirmishers attack near map spawn point. You will see how arrows stuck

**Comment by dorkster** [comment]
Ok, I see now. Like I said, those tiles could be marked as pits so that arrows can pass over them. However, I personally think it's fine to have an invisible "wall" there, as it is the map boundary.

Either way, this can be fixed in data and the engine is behaving as expected.
