### ISSUE TITLE
screen freezes after clicking menu and during map loading

### ISSUE THREAD

**Issue by sudoman** [clintbellanger/flare-engine#1350]
i'm not sure what should be displayed during these times, but it would be fancy if the mouse could still move.

other possible behaviors could include a teleportation effect, a blank screen (with moving mouse), a dark screen with some words, or an image, etc.

**Comment by dorkster** [comment]
I don't think there's much we can do about this:

- Flare is single-threaded, so we can't have asset loading in one thread and loading screen interaction in another. We will not be making Flare multi-threaded.
- Even on slow systems loading screens are relatively short, so displaying text or images feels like a waste.

You might prefer turning on "Hardware mouse cursor" in the Interface options, since that cursor is rendered at the OS / display manager level and can move freely during loading.

**Comment by sudoman** [comment]
personally i like the custom cursor, but i think your reasoning is quite sound. the loading times are very brief, so it's no big deal. :-)

**Comment by sudoman** [comment]
what about hiding the cursor? if you want to get fancy, you could also display something simple on the screen so the user knows the game isn't broken or frozen.

**Comment by dorkster** [comment]
Hiding the cursor isn't really an option. Once we trigger loading (aka map transisition), the screen does not get updated until after the loading is finished. So that includes our software cursor. As stated before, something like this would likely require multi-threading, which we're not doing. So I'm going to mark this as "won't fix".
