### ISSUE TITLE
MapSaver build fails on Windows with Visual Studio 2013

### ISSUE THREAD

**Issue by henrik-m** [clintbellanger/flare-engine#1353]
The reason seems to be an invalid operator pair for "<<" . The failing line was introduced in commit 52f646ecc9460d9350b9bb1902eb51d7e9bb9f1a. I added a note to the commit at the location of the issue. Was not sure how Github handles line notes in commits so I opened this issue too.

I'm not sure if this is a cross-platform or compiler version issue...

Dev System specs:
Windows 7 SP1
Visual Studio 2013 Community Edition

**Comment by igorko** [comment]
Did you add Mapsaver to build manually? By default MapSaver class is not used when building flare

**Comment by henrik-m** [comment]
Yes, sort of. I didn't use cmake but created a new VS solution "from existing files", and so Visual Studio scooped them up too. After I excluded MapSaver everything builds fine.
I'm curious though. Is MapSaver not meant to be valid code atm? Or am I the only one seeing this error?

**Comment by dorkster** [comment]
MapSaver (and whatever else ends up in the `src/api/` directory) are meant to be used when creating external programs that want to adhere to Flare's data structures. MapSaver in this case has been used in the [Random Map Generator](https://github.com/Paul-Wortmann/Random_Map_Generator).

However, I can't speak for the state of MapSaver's code on WIndows, since I've only ever tested it on Linux.

**Comment by igorko** [comment]
Fixed in https://github.com/clintbellanger/flare-engine/commit/b52610fe116c07d9e72540b6243010435c9f934b

**Comment by henrik-m** [comment]
And broken again by 0a1857f7c0ed38e30b9ec94f6c03e204955039a0. This time for all platforms. The maprow type no longer exists in Map.h
