### ISSUE TITLE
Remove SDL_gfxBlitFunc.c and SDL_gfxBlitFunc.h

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1380]
Can't check now compilation, but iirc these were used only for SDL 1.2 implementation. If I am right, they should be removed.

**Comment by igorko** [comment]
Hm, they still are used in software renderer, in renderToImage() only. Is there a reason why here only, can we drop it?

**Comment by dorkster** [comment]
Well, there used to be an issue with blending surfaces when the bottom surface was transparent. But that issue seems to have disappeared, so I guess we can drop the SDL_gfx files.

One thing about SDL_gfxBlitRGBA() is that it increased the "brightness" of the surface being rendered by shifting a portion of the alpha channel up. This made our text appear more bright, but we couldn't recreate this for the hardware renderer. So dropping it will make things more consistent across renderers, even if it looks strange compared to what we're used to. In flare-game, we can compensate a little by brightening the colors in `mods/fantasycore/engine/font_colors.txt`
