### ISSUE TITLE
Notable performance drop when using combat text

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-engine#1381]
At last I have tried Android version after dynamic resolution changes and switching to hardware rendering. But when Combat text is enabled, I get low FPS when fighting with like 5 enemies... Don't know if it happens on software rendering and if it was so notable before, but maybe we can improve combat text performance somehow.

**Comment by igorko** [comment]
To test try some massive attack, that targets few enemies(e.g. Quake)

**Comment by clintbellanger** [comment]
Each frame the CombatText updates the label, as its position moves

https://github.com/clintbellanger/flare-engine/blob/master/src/CombatText.cpp#L126

This set() function calls the label refresh() each time anything about the label changes.

https://github.com/clintbellanger/flare-engine/blob/master/src/WidgetLabel.cpp#L139

That's incorrect logic. refresh() should be called in fewer situations -- when the cached text image needs to be changed. The content of the label, not its position. 

So if you deal 10 damage, that "10" is being re-rendered by the font library each time in very slow detail, only because we're moving it up the screen. That "10" should be rendered once, and the cached label moves up the screen.

I think the internals of WidgetLabel need to be updated to fix this. Call refresh() in fewer cases, and/or add the "did the text actually change?" checks inside refresh() itself.

**Comment by clintbellanger** [comment]
Interesting catch by the way -- as these are one of the few labels that move position each frame.

As a reminder: using the font library to render alpha transparency fonts is expensive. So inside WidgetLabel we render it once to a Sprite, and then draw that sprite each frame. 

WidgetLabels for CombatText are floating upwards. Each time their y position changes, the big set() function for labels is called. (really, CombatText could just call setX and setY, as that's the only thing it changes each frame).

Take a peek inside WidgetLabel and you'll see that refresh() is called all over, and not just when the visual content of the cached text needs to be changed. Updating a label's X, Y position, or Justify, shouldn't require a label refresh().

Maybe we can rename WidgetLabel::refresh() to make that more apparent -- recacheTextSprite() or something. It's a private function, it can be that specific. Or put all refresh() calls behind another internal updateTextContent(text, color, font) function for sanity reasons.
