### ISSUE TITLE
List with resolution settings is displayed in the upper left corner

### ISSUE THREAD

**Issue by hansjoachim** [clintbellanger/flare-engine#1383]
Steps to reproduce
1. Main menu -> Configuration
2. Observe the settings.

Expected result:
Settings displayed in an orderly fashion

Actual result:

![settings](https://cloud.githubusercontent.com/assets/3002493/7105657/fdd4c446-e123-11e4-9759-1149794d34d8.png)

In 2211d22a6a6b33876928c274d01d6155426e18bd, the list for possible resolutions is displayed in the upper left corner, hiding other tabs. Not sure when this broke, but I distinctly remember this being shown inside the box in earlier revisions.

Tested this withe the revision mentioned above, just flare-engine alone without any additional mods. To make sure this wasn't somehow caused by an older settings file I had laying around, I removed ~/.config/flare. I belive this should be equivalent of flare out of the box.

**Comment by dorkster** [comment]
Strange, that list box is not in the engine at all anymore. Here's what my config menu looks like on the current master:

![2015-04-12_090622](https://cloud.githubusercontent.com/assets/913982/7105695/4697dcee-e0f3-11e4-82f9-e54aa69fff6a.png)

You can check your copy of the code by searching GameStateConfigDesktop.cpp for `resolution_lstb`. If there's code with that variable, then it's out of date and I suggest doing a 
```
git reset --hard upstream/master
```

Also, if you previously copied the default mod to another directory for running Flare, you'll need to copy it again because the config menu layout was updated there. Personally, I symlink the default mod in my local Flare data directory, like so:
```
cd ~/.local/share/flare/mods
ln -s ~/Projects/flare-engine/mods/default default
```

**Comment by hansjoachim** [comment]
Thanks for your comment.

This turned out to be a user error. I've created a build directory to keep those files mostly separate from the source files. So I had `flare-engine/build` which contained a freshly built binary, but I was running `flare-engine/flare` which was from an earlier build. (I was certain I had set that up as a symlink but turned out to be a binary a few months old.) Presumably the list in question was still in the options menu when it was built. 

I've retested with the latest binary and I no longer see this issue.
