### ISSUE TITLE
flare briefly freezes before zombies spawn from the ground at spawn point

### ISSUE THREAD

**Issue by sudoman** [clintbellanger/flare-engine#1385]
it only lasts a small fraction of a second, but it is somewhat noticeable.

**Comment by sudoman** [comment]
also, it only happens for the first spawned zombie after the map is loaded. the freeze still happens if one leaves and returns to the map during the same game session.

**Comment by igorko** [comment]
Well, noticing some delay when summoning zombies using noname mod undead summoning spell.

**Comment by clintbellanger** [comment]
If a new enemy is introduced that wasn't already on the map somewhere (e.g. summoning a creature type not already in the zone), the sprite is loaded from disk. That's the delay you're seeing, loading the image file.

I've seen similar issues in other games too, e.g. Torchlight.

There are ways to fix it, but these may seem like overkill.

1. We could support loading images in separate threads, so that the rendering loop can continue if bigger assets need to be loaded during gameplay. That's complex, and doesn't solve the issue that we want to start drawing right away.

2. We could check for any creatures which *might* be summonable and load the extra art when the map loads. Problem is, we want to support all kinds of weird ways to summon: items, events, etc. The ways I can think of checking this are all convoluted.

3. Show modders how to get around this: put that summoned creature somewhere on the map. That way the creature will load a copy of the art when the map loads, so it won't have to load it right when its needed.

**Comment by dorkster** [comment]
@clintbellanger Covered everything I was about to say. It's unfortunate that none of the solutions are good, but it's not really a major issue in my opinion.

**Comment by stefanbeller** [comment]
4.) Introduce some kind of property of the map which tells the engine which things to preload.
This would give the modder/game designer a fine grained option to steer what to preload and what not.

(graphics for story sequences/peaceful creatures may have these delays? or if you have diverting branches of game play you don't want to load all of them but only a few common types, though that's best solved having different maps)

Not sure I want this complicated thing in the UI, so maybe better go with 1) which is not complex IMHO but just a exercise of patience to find&implement all of the paths.

**Comment by dorkster** [comment]
Keep in mind persistent powers that allow the player to summon monsters on any map. Defining per-map preload settings won't work there.
