### ISSUE TITLE
Google Summer of Code Contributor

### ISSUE THREAD

**Issue by AustinHaugerud** [clintbellanger/flare-engine#1423]
Greetings, I'm submitting this more or less as a application. 

  I'm a first year CS student at Lewis Clark State College. This summer I'd like to be a full time contributor to Flare through Google's Summer of Code. 

  The best route to take I feel would be for me to start contributing to Flare part time before the summer begins, then contribute full time for the summer.

  To do this it would require not only for me to apply, but also for the Flare team to apply as a mentoring organization. If either of our applications were denied, I'd still be happy to be a contributor, I just would not be able to work full time. In case you feel that Flare isn't likely to be accepted, I'd like to point out that open source games have been accepted before i.e Battle for Wesnoth. While obviously I can't guarantee Flare would be accepted, I think it certainly has a fair chance. 

Some background information about me.

  I'm primarily a C++ programmer, and have been seriously using it for approx. 3 years. Most of my hobby code time has been with game programming. The first game I ever created was an ugly Battleship style game. I'm fairly certain if I looked at the source code to it now I'd cry as I was a pretty awful programmer at that time. 

  Over time though I've rigorously worked on improving. Most of my experience now is with engine development rather than implementing game play features. After I had made my Battleship clone and a very basic space shooter in high school I wanted to learn how to write a tilemap engine. I wrote a limited map editor (not an actual game) that worked fairly well for its intended purpose, however it turned out to be very hard to extend and became too unmanageable. I kept playing around with things however, and eventually I actually tried to start on a real game with a team. 

  I was an engine programmer along with one other, and a host of artists and even a musician plus a sound engineer. We made some neat progress, but eventually the cooperation fell apart and since then that project has been dead. After that, I started to realize I needed to start working more on making my code neat and extendable with good design patterns, so I started reading more books and articles etc. (Game Programming AI By Example, gameprogrammingpatterns.com, Game Engine Architecture, I'm reading Game Scripting Mastery currently) The main two things I did after this were: 

```
1.) Learn about isometric tilemaps
2.) Play around a bit with 3d graphics in irrlicht
```

  I did some pretty limited work with both. I made an editor that could render iso maps and had its own binary file format etc. ( I didn't intend to make a game, I most likely would have used Tiled if that was my goal). Flare was actually one of my main sources for learning about iso engines. 

Now I'm here in college as a CS student. I hope I can gain some skills with working in a team, and also contribute to a project that proved pretty helpful to me in the past. 

Thanks for reading! -Austin Jenkins

**Comment by igorko** [comment]
Hello Austin. I'm glad to hear that we can have more people in our team. It's very cool!

I can provide you a list of tasks that are in our wishlist, or planned to be made in future, but we have no resources to implement them. Feel free to select some and discuss here.

As of Flare v1 Engine, it's mostly complete, the only two things that stop us from releasing are: we wait for SDL2.0.4 release, and wait for finishing empyrean_campaign which will be official Flare v1 game mod.

We have some issues that are marked as "post v1" here https://github.com/clintbellanger/flare-engine/issues?q=is%3Aopen+is%3Aissue+milestone%3APost-1.0 . If you want, you can look into them and work on some, you can leave a comment and we will decide if we can include that feature in v1. But these are not huge tasks, and I guess don't deserve to be a topic for GSoC. If you want to become more familiar with engine, feel free to take some.

As of Flare v2, which we internally call "Flare next generation", https://github.com/dorkster/flare-engine-next, there are a lot of stuff that could make the engine more awesome. (and some of them can be a real task for GSoC)
Notes for some issues:

https://github.com/dorkster/flare-engine-next/issues/24 : There is some progress, @wolfpirker initially started to work on this, latest work is present in branch https://github.com/dorkster/flare-engine-next/tree/weather

https://github.com/dorkster/flare-engine-next/issues/9 : In context of this issue I have written openGL renderer for flare here https://github.com/igorko/flare-engine/tree/openGL . Renderer is almost finished (few minor issues left that don't block work on lights). But this issue is not "clean programming" issue. Work that is left consists from 1. writing correct shaders that will provide nice dynamic lights 2. generating textures that will show shaders in work. Currently we have test shader and test textures that show lights in work, but formula is too simple and generated textures are too bad.

https://github.com/dorkster/flare-engine-next/issues/12 : this one can be a real challange, no idea how this can be done ;)

Also see remaining issues, this one https://github.com/dorkster/flare-engine-next/issues/10 is imho very cool.

**Comment by AustinHaugerud** [comment]
Many of these issues look very interesting! I have studied flare v1 a bit before, but I haven't looked at flare-next so I'll make sure to take some time to look at that. Some of these issues aren't in my area of expertise ( like the OpenGL renderer, my experience with OpenGL is limited ) but from what I can see there's plenty to do. How does the Flare team primarily communicate? I've gone onto the IRC channel before, but it seems to never be active.

**Comment by AustinHaugerud** [comment]
As an extra note, some of the currently opened issues for Flare I feel would be much more easily solved if Flare had a solid scripting system in place (For example, adding wandering NPCs). The book I'm reading right now is dedicated to game scripting systems whether it be integrating Lua/Python or even creating a new scripting language altogether. I think it'd be very good to work on adding Lua scripting to the engine, I think that'd be good to call a high priority project.

**Comment by stefanbeller** [comment]
:+1:

**Comment by igorko** [comment]
We communicate mainly using google account in jabber. I have not used IRC for long time already, but if it will be needed for some group conversation, I can be in IRC too.

**Comment by igorko** [comment]
@AustinHaugerud , btw, the only difference between engine and engine-next currently is that engine-next has opengl renderer (separate files). The rest of code is similar.

**Comment by AustinHaugerud** [comment]
I'm fine with using jabber, I just need some info on how to join you there.

**Comment by dorkster** [comment]
FYI, Google dropped Jabber/XMPP support from their chat protocol. Nowadays, it's Google Hangouts.

I can also get back on the IRC more often.

**Comment by AustinHaugerud** [comment]
I'm fine with hangouts or IRC, you guys just let me know where I need to be, I'm not too worried about it haha.

**Comment by igorko** [comment]
I will try to be in IRC, but this week not too often.

**Comment by AustinHaugerud** [comment]
Update: I'm going to quote the email I sent Clint. I felt I should include everybody in this conversation.

>First off, I apologize if I've seemed rather quite concerning Flare development. I've mostly just spent the time I've had experimenting with the Lua scripting layer in the engine. Due to college,one other project, and work, my time has been pretty split. I've been taking my time working on the Lua integration for those reasons and also due to caution, as it it's a pretty big feature and I don't want to clumsily throw any major design flaw(s) in it because I wasn't well organized and didn't plan ahead, document what I did etc. The Flare team seems to not be overly communicative anyways, so hopefully this hasn't seemed an issue. 

>With that said, I just wanted to remind you if you're still interested in the Google Summer of Code, mentoring organization applications are approaching (submissions open Feb 8th). If you're accepted, I will apply to be mentored and working under the Flare project. One other benefit is that if Flare is accepted, Google will pay $500 to the project. I think it wouldn't hurt to at least apply. Other open source games have been accepted before, and IMO, Flare has a pretty good standing in the open source game community.

>Their FAQ is very informative if you have questions.

>https://developers.google.com/open-source/gsoc/faq?hl=en 

Somewhat related to the scripting layer, I've also been experimenting with developing easier ways of creating game content for the Flare engine (so it's not really attached to the engine's codebase). One thing that's very different for me working with Flare is the development TC. In my past projects, I've usually gone through the trouble of developing a single program that can build levels, link in music, etc. I don't think Flare needs a monolithic development environment, but I've been looking at the idea of adding some other tools that would help ease development. This is for another issue, but just my update on what the hell I've been doing the last few months, in case you guys were wondering what with my mysterious silence.
