### ISSUE TITLE
Rendering wrong priorities

### ISSUE THREAD

**Issue by TaiVuong** [clintbellanger/flare-engine#1424]
Shield render wrong priorities when attacking.
![untitled](https://cloud.githubusercontent.com/assets/12879647/10709114/7a51a686-7a4b-11e5-9dda-0367f171f350.png)

**Comment by igorko** [comment]
I guess with can't do anything with this. If hero will have knife in his hand, order will be ok (hand will be on top on knife). We don't separate shields and weapons and don't provide different rendering orders for them. I guess current behavior is better then you would see floating weapon on top of hand.

**Comment by clintbellanger** [comment]
For now to simplify things, the layers have a specific draw order for each facing direction. It works most of the time, except in cases like this where the character twists around too much in the middle of an animation.

This could be fixed by allowing a draw order for every single frame, instead of one per direction. Also, can be worked around by tweaking the animations.

In this situation, it happens so fast that it doesn't bother me. The paper doll, one setup per direction system works 99% of the time, and that's okay with me for v1.0.

**Comment by TaiVuong** [comment]
I think that problem can resolve by changing postures like this 
![untitled](https://cloud.githubusercontent.com/assets/12879647/10711122/35b43510-7a9c-11e5-8469-58c2527f234c.png)

**PS:** as @clintbellanger  say, it's not big issue. No need to fix.

**Comment by TaiVuong** [comment]
There are many free 3d models at https://www.mixamo.com/
I think it'll make u finish v1.0 better and faster.
