### ISSUE TITLE
movement froze and arrows began shooting in rapid fire

### ISSUE THREAD

**Issue by sudoman** [clintbellanger/flare-engine#1448]
As I was shooting a goblin with a bow and arrow it performed a magical attack. Suddenly movement froze and a stream of end-to-end arrows appeared in front of my character. The arrow attack sound began repeating very frequently. A second or two later game play resumed as normal.

**Comment by dorkster** [comment]
Ignore the fix I just added, since it doesn't seem to actually do anything in practice.

When you say "movement froze", do you mean only your ability to move the hero? If so, then at least my assumption that this has to due with the player being stunned is okay.

On the other hand, if *everything* froze, then it's possible that the game took longer than desired to load the graphics for the magic attack the goblin used. This would make the game lag and cause frames to be skipped, which would probably result in rapid arrows/sounds.

**Comment by sudoman** [comment]
it was the ground-stomping attack (stun?). the graphic for the motion was complete or almost over when it happened. i lost the ability to move the character, but i don't know whether anything else was moving aside from arrows quickly (possibly instantly) appearing on the screen.

**Comment by dorkster** [comment]
> it was the ground-stomping attack (stun?)

Yes, that is an attack that causes stun. If the arrow attack sound repeatedly played, that means you were on the first frame of your attack animation. I'll have to do more testing under that scenario.

**Comment by hansjoachim** [comment]
I've experienced the same issue. It is rather hard to trigger, but happens occasionally. 

When characters are hit by "quake"-like powers, for instance the quake from Goblin shakers or a Thunderstrike, it looks like they get stuck/stunned for a short time. The stun lasts about a second or so, in which the character is unable to do anything. It seems like when characters are stuck like this, they are in fact repeating whatever action they did when they got hit. 

I first noticed that shouts or other sounds would "echo" or repeat very rapidly when hit by these effects. However, I've also had other actions repeat, like attacks. One time my scout got stunned mid-attack, and when the attack looped he fired a continous line of arrows. I wasn't sure whether these arrows were just the animation playing or whether they would have actually done any damage until the same thing happend to my adept. In that case, getting stuck allowed him to send a stream of spells straight at Mez. The boss, which had been at ~80% health, died almost immediately.

So the problem seems to be when characters get stunned, they don't freeze, but keep repeating their actions which might have consequences.
