### ISSUE TITLE
Option for Additive blending for powers?

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#1494]
Right now all the images we draw use normal blending when layering on top of some existing image. In SDL there's support for a couple other Blend modes that are useful in specific cases. Links to some of the specs:

https://wiki.libsdl.org/SDL_SetTextureBlendMode
https://wiki.libsdl.org/SDL_SetSurfaceBlendMode

The main one I want to use is Additive blending, and the main place I want to use it is on Powers. Spell effects that are supposed to be Glowing look far better when using Additive blending instead of normal blending. Here is an example using the Channel power art:

http://i.imgur.com/mih2e64.png

The sprites on top are normal blending, and the bottom are additive. Notice the top sprites have darker edges, when we want it to be softly glowing like the bottom.

I propose a new option in Power animation files like this:

    blend=add

And something like blend=normal is the assumed default.

Not necessary, but it's okay if this Add blending option is available on any animation and not just Powers. Example, ghosts or wraith enemies could only be done well with this effect.

**Comment by dorkster** [comment]
Are you sure what you want is additive blending? Additive blending would give sort of a translucent effect because we're using the color information from behind (see screenshot).

![screenshot_2017-05-19_17-09-15](https://cloud.githubusercontent.com/assets/913982/26267272/3c430a6c-3cb7-11e7-9251-4325178c14cc.png)

For the effect you want with the Channel art, couldn't you better accomplish that by increasing the brightness/contrast of the Channel image itself? I was able to closely match your image with brightness = 100 and contrast = 50 in Gimp. The advantage of doing this is the colors from behind won't bleed through.

If you still think this feature is worth pursuing (there *is* a neat ghost-like quality to the screenshot I posted), I think this should be done at the Animation/Renderable class level. That way, anything that's animated (except map tiles) can take advantage of it.

**Comment by clintbellanger** [comment]
Yes this is the exact effect we want, applied to specific animations like magic and lightning. And some kinds of fire (e.g. if a fire needs thick black smoke this isn't best -- in those cases the fire and smoke should be separated into blend styles).

Changing the brightness/contrast of the original image can't give the same result. Additive means every pixel will get brighter, which is what is desired in an effect that is its own light source. Translucently lighting up the pixels behind it is what sells the effect as bouncing light into the environment.

Also additive blending means that when these glowing sprites stack, they get even brighter. This is nice and magical feeling. You can see this happening internally in the Channel sprites as the inside of the blast is bright because of the particles being close together (cause I use Additive blending when rendering these sprites in Blender). You see this in other games where stacking many fiery explosions together makes the middle of it go blinding white.

**Comment by clintbellanger** [comment]
For a vivid comparison, consider Diablo 1 vs Diablo 2. Diablo 1 didn't use additive blend mode for effects and Diablo 2 did. Compare how the Fire looks:

D1 https://www.youtube.com/watch?v=CspdaPBB9Z8
Notice that stacking fire doesn't make it brighter, and the edges of the fire sprites are too dark.

D2 https://www.youtube.com/watch?v=XY81NaJD8pA&t=2m20s
Notice that the fire is fucking rad

**Comment by dorkster** [comment]
>Notice that the fire is fucking rad

Noted :)
Thanks for the explanations.

**Comment by SarcrofS** [comment]
Hey, look at print of @dorkster this can be useful for poisoned, slowed (by cold) like in Diablo 2?
Exemple:
https://vignette2.wikia.nocookie.net/diablo/images/b/be/Amazon_with_Venom_rune_word.png/revision/latest?cb=20151018011516

**Comment by dorkster** [comment]
@SarcrofS That could be achieved with color modulation. SDL provides `SDL_SetSurfaceColorMod()` and `SDL_SetTextureColorMod()`. If we implemented that, I think it should be a property of Effects, since the color modulation would only happen on a target player/enemy, just like in Diablo 2.

**Comment by SarcrofS** [comment]
Nice, changing stealth to this with a more invisible style and not a new sprite would be cool too 🗡

**Comment by dorkster** [comment]
@SarcrofS We'd use `SDL_SetSurfaceAlphaMod()` for that, but same idea. The Stealth power in the alpha_demo is more of a demonstration for transformation powers, but for general buffs to the Stealth **stat**, changing the player's alpha would be nice.

**Comment by dorkster** [comment]
Everything in this thread has been implemented in 81efcf415d490ecf557b2f970aac9616e462020f and eb8b45d1321b774773050a24511b750ba0051fb4

Here is a preview video showing additive blending on the Channel power, as well as the Stealth effect re-created using only `color_mod=0,0,0` and `alpha_mod=127`.

**Comment by dorkster** [comment]
I wanted to try out using color mods as a sort of quick and dirty alternative to palette swaps. For example, fire and ice skeleton mages can have slight red and blue tints respectively. Since Effects get removed on death, any applied color mods would disappear when the entity died.

So for more flexibility, I've [added support](https://github.com/clintbellanger/flare-engine/commit/db9ea92550755a75e3b0e7ecd3d698fb422dfe56) for `color_mod` and `alpha_mod` into the header section of Animation definitions, just like `blend_mode`. This means we can use these properties on animations that normally wouldn't be affected by Effects, such as Powers, NPCs, and Loot.
