### ISSUE TITLE
How is SDL in flare?

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1552]
Is SDL packaged in Flare?
From the contents of the Issue https://github.com/clintbellanger/flare-game/issues/570 , I felt as if SDL was packaged in Flare.

If packaged in, what folder is the SDL in?

And it is the another idea, since SDL was updated in December 2017, I think that it is more better that Flare also  uses SDL's latest stable version.
If so doing, Flare can appeal further contributions to the SDL community.

**Comment by dorkster** [comment]
We do not include SDL2 in the the flare-engine repository. If you build from source, you must provide your own copy. On Linux, this can usually be provided by your distribution. For binaries, it depends on the platform:

- Linux: Since Flare binaries are done by each distributions package maintainer, they are built against that distribution's version of SDL2. So if you use Fedora, you'll be using Fedora's package for SDL2.
- Windows: We distribute the latest SDL 2 DLL files when doing a release. These are placed alongside the flare.exe file.
- Mac OSX: This is somewhat similar to Windows if I recall correctly.
- Android: I pull the latest SDL2 code from their Mercurial repo, since building Flare on Android requires compiling SDL ourselves.
