### ISSUE TITLE
How is Python3 compatible problem in Flare?

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1553]
I felt that the grammar of Flare-game seems to be written in python. Is it necessary to use Python when making games with Flare-engine?
Or can Flare-engine be available in other scripting languages besides Python?

Also, python is not compatible with version 2 or earlier since 3. How is the python code in Flare about this Python compatible problem?

**Comment by dorkster** [comment]
Flare data files are in a plain text format similar to [INI files](https://en.wikipedia.org/wiki/INI_file). Github says flare-game is Python because we have a Python script for generating language translation files. Github doesn't recognize the INI files as code, so it doesn't count them.

I believe the aforementioned translation script is written in Python 3. It invokes `/usr/bin/python`, which points to python3 on my system, and it works perfectly. It might also work with Python 2, since some Python 3 code is backwards compatible if you avoid certain functionality.

**Comment by sujiniku** [comment]
Let's write this thing in the README. Otherwise, the programmer who came to see Github misunderstands it.

**Comment by dorkster** [comment]
We already have this in the flare-game README:

>Flare uses simple file formats (INI style config files) for most of the game data, allowing anyone to easily modify game contents. Open formats are preferred (png, ogg). Maps are edited using Tiled.
