### ISSUE TITLE
Feture Request: Limiting the number of saved game

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1565]
Now the saving mechanism of this engine is that can increase the number of saved game any number.
But I think that it is safer to limit the number of saved game.
Also, if we are still able to create saved game any number, there may be a hole of security that it is cracked with overflow attack etc.
Therefore, for example,  I think that limiting the number of saved game until about 30 pieces per game is better.

**Comment by dorkster** [comment]
Flare saves are currently limited to a range of 1 to 2147483647. Any overflow in either direction results in a negative value, which we ignore. If you're worried about buffer overflows, we use STL containers. So an exception would get thrown if allocation failed or there was incorrect access.

Due to Flare's modding nature, there are several points where malformed input could causes issues in game. We do our best to mitigate these, but we also tend not to worry too much about them.
