### ISSUE TITLE
What is "Latest release"?

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-engine#1577]
At 
http://flarerpg.org/index.php/download/

"Latest release" is written "0.19 " , but, is true latest release  0.20 , isn't it?

**Comment by dorkster** [comment]
There was a point where we thought we were ready to move towards 1.0. I had tagged 0.20 as being our "release candidate" version. Obviously, plans have changed since then.

The last proper release with compiled binaries was 0.19.

With 1.0 actually releasing very soon, there's no point in going back to make binaries for 0.20.
