### ISSUE TITLE
"Respec" option?

### ISSUE THREAD

**Issue by tvleavitt** [clintbellanger/flare-engine#1622]
As per #1621; I wound up accidentally misallocating Skill points in the "Powers" tab. It would be useful to have some kind of "respec" option to correct errors like this.

**Comment by dorkster** [comment]
We have such functionality in the developer console, but there's no way to trigger it normally in game. Maybe an Event property would be appropriate for this. That way, you could talk to an NPC or use an item to trigger a respec.

One note about the developer console's respec function: The player is completely reset here, with **no** stat points allocated and **no** powers unlocked. So the respec Event property should contain a few options:

- reset to class defaults or engine defaults?
- what to reset: stat points + unlocked powers *or* just unlocked powers. We can't do just stat points, as that could break unlocked powers.
- reset the actionbar?

**Comment by clintbellanger** [comment]
The save files are basic plain text files. That's intentional, it's an open invitation for tweaking and respec'ing and cheating.

In Wandercall I'm thinking of having an NPC drop hints about editing save files being okay. I think you're right than an Event property is the best general purpose solution.

I'm guessing the best way is to reset all spent points (stats and powers). And go through the action bar slots and clear out anything that no longer meets requirements. Or disable those slots with an additional mouseover note "requirements not met"

**Comment by sujiniku** [comment]
Sometimes I also mistake raising other parameters I do not want to raise.
So I think that it is better to show a confirmation dialog after parameter distributing of stats.

For example, Such as "Do you change stats? Yes / No " should be shouwed.
until the player press Yes, Flare should avoid updating stats.

For that purpose, in addition to the stats after level up, stats at the present time should also be showed in "character" window.

If someone creates a game like "Wizardly" in the future, if flare have such a confirmation dialog, it is convenient for character making by the player.

**Comment by elosha** [comment]
I like the idea of making it possible to respec in the game, but to make it "hurt", in order to endorse you to think twice.

In an older version of World of Warcraft, you could talk to an NPC, it cost gold and the price raised each time until a higher limit was reached. It was not fatal to choose a wrong spec in the beginning or to try something out, but it prevented abuse.

**Comment by dorkster** [comment]
Implementation here: https://github.com/clintbellanger/flare-engine/commit/4474866b05ed67a682d318af84ef9a37197e4abe

Usage examples:

```
# resets xp, and loads default stats and unlocked powers from the player's class
respec=xp,false

# resets stats and unlocked powers to engine defaults
respec=stats,true

# resets unlocked powers via loading the powers from the player's class
respec=powers,false
```

The `respec` command in the developer console has been removed, as respeccing can be done from the console with `exec respec=...`
