### ISSUE TITLE
Feature idea: Interaction in books via Events

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-engine#1625]
Books could become really flexible if we add support for executing Events when clicking on an area.

Ideas:

- an interactive map where clicking on a location teleports the player there
- we could simulate multiple pages by opening another book as the next page
- for games with a modern setting, the "book" could function as an interactive computer screen
- if we also add support to control the images displayed within a book via statuses, it may also be possible to give some matching output for the player's input (i.e. a keypad to unlock a door)

**Comment by sujiniku** [comment]
To divide money to shared stash, I want a keypad that can be inputted numerical values.
I will be able to enter money I can deposit in the stash with only just the mouse.

" "half" button or "one-quarter" button, for item dividing by shift key " #1601

**Comment by dorkster** [comment]
@sujiniku That wouldn't be related to this feature, which is about the MenuBook class. For what you describe, we would need to extend the MenuNumPicker class.

**Comment by sujiniku** [comment]
I think that individual features developed by this "books via Events" feature should be handled like plug-in so that it can be used for game development other than flare-game.

**Comment by sujiniku** [comment]
I hope that @dorkster makes these mini games for demonstration these individual features.
So, with using flare-starter-pack. If possibel, please make the individual games which is derived from flare-starter-pack is incorporates these feature.

Empyrean_campaign is too long in oeder to demonstration these features.
It is inappropriate to do these demos with because the game is too long.
Also, it does not match the world view of the empyeran.
For example, A door with a secret number will not exist in the world of empyrean.

**Comment by dorkster** [comment]
The engine features needed for this have been implemented:

- 5c77da5f2df1784304394fbc9dcdad27b7daf3d4
- 23fb3bbeae9dcc27918e27cb09d9721adec60f34

I've also made a short demonstration video: https://youtu.be/JwGq9-y-Y-c
