### ISSUE TITLE
Crash on game exit

### ISSUE THREAD

**Issue by flaviojs** [clintbellanger/flare-engine#1631]
Flare v1.0 crashed on exit with:
```
ERROR: AnimationManager: Still holding these animations:
ERROR: animations/powers/spark_blue.txt 1
flare.x86_64: /home/justin/Desktop/flare-engine-v1.0/src/AnimationManager.cpp:55: AnimationManager::~AnimationManager(): Assertion `names.size() == 0' failed.
./flare.sh: linha 21: 21318 Abortado                (imagem do núcleo gravada) ./x86_64/flare.x86_64 "$@"
```

I was in Grot Lagoon. When I killed the boss, I saved and exited to go sleep. When I saved there were enemies attacking me.

Probably unrelated, but I was running flare with "--renderer=sdl".

**Comment by flaviojs** [comment]
Got the same with Flare 1.01:
```
ERROR: AnimationManager: Still holding these animations:
ERROR: animations/powers/spikes.txt 4
flare.x86_64: /home/justin/flare-engine/src/AnimationManager.cpp:55: AnimationManager::~AnimationManager(): Assertion `names.size() == 0' failed.
./flare.sh: linha 21:  5659 Abortado                (imagem do núcleo gravada) ./x86_64/flare.x86_64
```

This was in "Underworld Stronghold: Foyer". I'm using Haste after the spikes, so maybe it's something related to screen visibility?

**Comment by dorkster** [comment]
I found what the problem was. Consider the following order of events:

1. `HazardManager::logic()` checks a queue called `hazards` that's part of the `PowerManager` class for new hazards. The queue is cleared in this process.
2. `PowerManager::activate()` is called. At this point, this can happen if an entity is hit with a power that has a post_power (spark_blue.txt) or if it's triggered from a map event (spikes.txt). The hazard's animation is loaded here.
3. Step 1 is prevented from occurring on the next frame. Either the pause menu is opened, or the game window is closed.
4. The `hazards` queue is not empty, resulting in the animations in step 2 to still be loaded. When the `AnimationManager` is deconstructed, our assertion fails.

I have verified this by adding an assert for the `hazards` queue size to the PowerManager deconstructor and forcing the game to exit when step 2 happens.
