### ISSUE TITLE
Accuracy can go over 100%

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-engine#1659]
I had this odd situation in Flare 1.06 + Empyrean Campaign:
https://i.imgur.com/3TCSadF.jpg

Why is accuracy over 100%? How is accuracy calculated? I think this needs to be re-thought. :-/

I had no accuracy-modifying items equipped and also no accuracy-modifying abilities.

**Comment by dorkster** [comment]
This is intentional. The effective accuracy is:

```
source_accuracy - target_avoidance = real_accuracy
```

The player starts with 85% accuracy, and is grated 3% per level and 1% per Offense. Hence why you have 107%. If you attacked an enemy with 30% avoidance, your effective accuracy would be 77%.

IIRC, this system is similar to the game Andor's Trail.

**Comment by Wuzzy2** [comment]
I really wish there was something like a player manual which explains stuff like this. But this is getting off-topic.

Your definition still does not make sense. Looks like it's still possible to end up with a `real_accuracy` of over 100% if the `source_accuracy` is very high, and the `target_avoidance` is very low.

I still think it's wrong to say you have 107% accuracy. The standard Englishman understands “accuracy” as the ratio of number of times hit vs number of shots. So it can never be higher than 100%. Please don't redefine English words. ;-)

What you call “accuracy” in the game is actually not accuracy, but something very different. It's a variable which is used to calculate the “real” accuracy. This variable just does not have a proper name yet. “Accuracy rating”, maybe? I have no ideas.

Alternatively, drop the percent sign from accuracy and make it an unit-less number. That would seem more fitting.

**Comment by dorkster** [comment]
The "real" accuracy can in fact be capped to 100% with the `accuracy_percent` value in `engine/combat.txt`, though we don't do that for the Empyrean Campaign. We won't be changing any of the combat values, nor the entity accuracy/avoidance values. Even if we scaled it down so that enemies started with 0% avoidance, we wouldn't have the range we need. So going over 100% is just going to have to be accepted. There are other percentages that can exceed 100%, such as poise, elemental resists, item find chance modifier, etc.

I think we can improve the tooltip descriptions for some of these to at least expose some of the math to the player. For the sake of fitting it in the UI, I'd like to keep the name for Accuracy, but we can describe it as "Accuracy rating" in the tooltip, which I think is an apt description. And of course we should mention how the target's Avoidance is taken into account.

**Comment by Wuzzy2** [comment]
This issue is NOT about changing ANY mechanics! Actually, this is just about how this is presented to the player.
I think the way this is presented to the player right now is very flawed, as “107% accuracy” just doesn't make sense under standard English terms. :)
What I'm saying is, that it should be somehow shown to the player which is intuitive and (more or less) logical. I think this is possible without toucing any mechanics.

**Comment by dorkster** [comment]
So do you agree that adding descriptions of these stats to the character menu tooltips would be sufficient? Or are you still interested in changing the name of "Accuracy" and/or dropping the percent sign?

Personally, I think the current terminology makes sense because "accuracy" is used in terms of how well of a hit was made, instead of hit or miss. For Flare, an accuracy > 100% can represent "critical strike". We call them "overhits", and they have yellow damage text, but no screen shake like normal critical hits. Accuracy less than 0% can represent a near miss (but still a hit), which gets shown as grey damage text.

Maybe this is all just making more sense in my head. But I think if we describe the math behind all this in the tooltips, it ultimately won't matter what we call it.

**Comment by Wuzzy2** [comment]
I don't have a better word to offer, sorry.

Changing the tooltip would help already, yes. As long the tooltip doesn't become insanely long, of course.

**Comment by dorkster** [comment]
I've added tooltips for Accuracy and Avoidance (and some other stats that lacked description). How do these sound?:

>Accuracy rating. The enemy's Avoidance rating is subtracted from this value to calculate your likeliness to land a direct hit.

>Avoidance rating. This value is subtracted from the enemy's Accuracy rating to calculate their likeliness to land a direct hit.

**Comment by Wuzzy2** [comment]
Sounds good! :+1:
