### ISSUE TITLE
Allow shaking cam via powers

### ISSUE THREAD

**Issue by stefanbeller** [clintbellanger/flare-engine#687]
I am thinking the shaking cam would be a great addition to the quake stomp in flare-game.

**Comment by dorkster** [comment]
While not as elegant as a dedicated Power variable, shakycam can be triggered through Event scripts. And since Powers can call an Event script, a script that triggers shakycam could be used to achieve the desired effect. As Clint mentioned, this should be used sparingly, so I don't mind if creating such an effect is a little obtuse at first.

Example:

```
# scripts/shakycam.txt
shakycam=2s
```

```
# powers/powers.txt
[power]
id=1
script=scripts/shakycam.txt
```
