### ISSUE TITLE
Cannot reach text input field without a mouse

### ISSUE THREAD

**Issue by makrohn** [clintbellanger/flare-engine#724]
As I mentioned in #722, it is currently impossible to get to the text input field in GameStateNew if you're using mouseless controls.

Dorkster commented there:

"So far, we've mostly thought of mouse-less systems as systems that don't have a proper keyboard either, like the GCW-Zero. I think we could solve this by adding a way to toggle a WidgetInput's active state. In other words, press Enter to start typing, press Enter again to finish."

**Comment by dorkster** [comment]
SDL 2 has [SDL_StartTextInput](https://wiki.libsdl.org/SDL_StartTextInput), [SDL_HasScreenKeyboardSupport](https://wiki.libsdl.org/SDL_HasScreenKeyboardSupport), and [SDL_IsScreenKeyboardShown](https://wiki.libsdl.org/SDL_IsScreenKeyboardShown), which could help us handle this on devices without physical keyboards

**Comment by dorkster** [comment]
I've implemented Clint's idea of having Enter toggle WidgetInput's edit state. I also made a few improvements to WidgetInput in general. It's now possible to control the cursor position with the arrow keys as one would expect from a text entry field.

I know I mentioned getting the on-screen keyboard working for touch devices, but I'll consider that a separate issue and mark this one as finished.

**Comment by dorkster** [comment]
On-screen keyboard support has been added, so text input is possible on phones/tablets now. Since the keyboard usually covers up the area you're typing in, I've opted to display the WidgetInput text in a tooltip at the top of the screen (see image).

![screenshot_2017-08-18-16-51-21](https://user-images.githubusercontent.com/913982/29477363-32ad6d32-8436-11e7-99aa-995c157b798c.png)
