### ISSUE TITLE
Code Review for 1.0

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-engine#869]
Before we jump to the 1.0 label, I want to look at every source and data file in the project. The goals:
- Identify parts that can really use refactoring
- Determine whether that refactoring is 100% internal or if it affects data files
- If it affects data files, schedule the change for the Pre-1.0 milestone
- Identify any remaining hardcoded data that belongs in a config file
- Identify areas lacking source comments
- Identify missing error handling
- Identify missing error messages
- Identify weak or unused features that could be removed
- Consider renaming anything misleading
- Analyze Post-1.0 features to make sure we won't break data file specs later

**Comment by dorkster** [comment]
Just to give an update, I put together a change log summarizing what's been done since v0.19: https://gist.github.com/dorkster/8540906174e97cbe71da

Maybe it's time for us to bump to v0.20? This would be our "release candidate". Our current roadblocks for jumping straight to 1.0 include:

- The SDL 2.0.3 issue on Windows. Either we ship the dev version of SDL 2.0.4, or wait for the SDL folks to ship.
- We need game data to replace alpha_demo! I've been working on the Empyrean campaign periodically, but it's been slow. I think we need to start discussing how to get other people involved on that end, but without falling below the quality level we want.

**Comment by igorko** [comment]
I propose to release v1.0 RC (maybe after SDL 2.0.4 release, or even now),  for all supported platforms and on Google Play for Android. And I hope this will involve people to write mods and update current game data. And I would like to call it 1.0RC, not 0.20 or whatever, because 1.0 looks better for promotion.

**Comment by dorkster** [comment]
I'm fine with calling the release 1.0 RC publicly, but the actual engine version will be 0.20, since that will let us differentiate between this version and the actual 1.0 release at the mod level (the `version_min` and `version_max` keys in the mod settings file).

**Comment by igorko** [comment]
Just was reviewing versions history(in wiki) . We really need to release v1.0.  0.19 was released 1,5 years ago...

**Comment by igorko** [comment]
I propose to not wait for SDL2.0.4 and release 0.20 (1.0RC for public) without waiting for SDL team, as it can take monthes with currently opened 60 release stoppers.

From our side we need to take care about warnings and windows xp issue(I'll try to investigate it).
What do you think, guys? For Android and Windows we use SDL from mercurial, Linux and MacOSX builds can have note about SDL issue.

**Comment by igorko** [comment]
I hope we can release 0.20 engine soon, SDL 2.0.4 is almost ready. We should then announce string freeze and update all available mods: flare-game mods (should be ok), polymorphable, noname-mod(these should be mostly up-to-date as I have reviewed and updated them recently, but some minor changes happened last time on engine side which should be reflected on data side), maybe concordia, (if @pennomi or @makrohn still plan to develop it).

**Comment by dorkster** [comment]
I bumped the engine version to 1.0 today. Recent static analysis runs have been clean, and the only real "cleanup" work left would be to look at [all the implicit type conversion warning Clang spits out](https://travis-ci.org/dorkster/flare-engine/jobs/72034274). Nothing of real priority at the moment.

We could certainly do a string freeze and translations for the engine now. Game data translations won't be for a while, since I'm still working on creating the content in the first place.

We'll still be waiting for SDL 2.0.4 for our release, as it's needed for our Windows builds. For convenience, here are the [open tasks for SDL 2.0.4](https://bugzilla.libsdl.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=WAITING&bug_status=RESPONDED&bug_status=ASSIGNED&bug_status=REOPENED&keywords=target-2.0.4&keywords_type=allwords&list_id=12321&query_format=advanced).

**Comment by dorkster** [comment]
I just pushed a series of changes that improve how our [Attribute Reference](https://github.com/clintbellanger/flare-engine/wiki/Attribute-Reference) is formatted. This came about after discussions with @igorko about using this data to create a GUI for creating/modifying Flare mods.

The goal was to create a more concrete syntax for displaying parameters. Most notably, parameter descriptions are now separated from the parameters themselves with a colon. These are two separate XML attributes when exported to XML. This should make it easy to parse the parameters by themselves.

During this process, I had to make a few changes to the mod API. Here are the affected files:

- `menus/character.txt`
- `engine/font_settings.txt`
- `engine/xp_table.txt`
- `engine/stats.txt`, and likewise, files in `enemies/`. (I ended up writing a [script](https://gist.github.com/dorkster/a1c008059e4850a01fb3b5b2fcc43484) to update these.)

I have updated flare-game and sent pull-requests to the other mod repos.
